# Generated by Django 5.2.6 on 2025-09-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='images/'),
        ),
    ]
