# Generated by Django 5.2.6 on 2025-10-03 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examschedule',
            name='course',
        ),
        migrations.DeleteModel(
            name='ClassTimeTable',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='ExamSchedule',
        ),
    ]
